# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IRMA_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(1483, 755)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.HumRead = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HumRead.setFont(font)
        self.HumRead.setAlignment(QtCore.Qt.AlignCenter)
        self.HumRead.setObjectName("HumRead")
        self.horizontalLayout_37.addWidget(self.HumRead)
        self.gridLayout.addLayout(self.horizontalLayout_37, 6, 10, 1, 2)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.MagnetRead = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MagnetRead.setFont(font)
        self.MagnetRead.setAlignment(QtCore.Qt.AlignCenter)
        self.MagnetRead.setObjectName("MagnetRead")
        self.horizontalLayout_34.addWidget(self.MagnetRead)
        self.gridLayout.addLayout(self.horizontalLayout_34, 12, 10, 1, 2)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.LightRead = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LightRead.setFont(font)
        self.LightRead.setAlignment(QtCore.Qt.AlignCenter)
        self.LightRead.setObjectName("LightRead")
        self.horizontalLayout_36.addWidget(self.LightRead)
        self.gridLayout.addLayout(self.horizontalLayout_36, 8, 10, 1, 2)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setSpacing(1)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_41.addWidget(self.line_2)
        self.gridLayout.addLayout(self.horizontalLayout_41, 5, 8, 1, 4)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.gridLayout.addLayout(self.horizontalLayout_16, 17, 1, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.gridLayout.addLayout(self.horizontalLayout_13, 17, 3, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.NormImg = QtWidgets.QPushButton(self.tab)
        self.NormImg.setMaximumSize(QtCore.QSize(150, 50))
        self.NormImg.setObjectName("NormImg")
        self.horizontalLayout_15.addWidget(self.NormImg)
        self.gridLayout.addLayout(self.horizontalLayout_15, 17, 4, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.gridLayout.addLayout(self.horizontalLayout_17, 17, 5, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.BatteryLevel = QtWidgets.QProgressBar(self.tab)
        self.BatteryLevel.setMinimumSize(QtCore.QSize(0, 25))
        self.BatteryLevel.setMaximumSize(QtCore.QSize(900, 25))
        self.BatteryLevel.setProperty("value", 24)
        self.BatteryLevel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.BatteryLevel.setObjectName("BatteryLevel")
        self.verticalLayout.addWidget(self.BatteryLevel)
        self.gridLayout.addLayout(self.verticalLayout, 1, 8, 1, 4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 8, 1, 2)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_29.addWidget(self.label_7)
        self.gridLayout.addLayout(self.horizontalLayout_29, 10, 8, 1, 2)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_9 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_28.addWidget(self.label_9)
        self.gridLayout.addLayout(self.horizontalLayout_28, 14, 8, 1, 2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.gridLayout.addLayout(self.horizontalLayout_11, 12, 8, 1, 2)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_30.addWidget(self.label_6)
        self.gridLayout.addLayout(self.horizontalLayout_30, 8, 8, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.gridLayout.addLayout(self.horizontalLayout_8, 16, 8, 1, 2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.AltRead = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AltRead.setFont(font)
        self.AltRead.setAlignment(QtCore.Qt.AlignCenter)
        self.AltRead.setObjectName("AltRead")
        self.horizontalLayout_12.addWidget(self.AltRead)
        self.gridLayout.addLayout(self.horizontalLayout_12, 16, 10, 1, 2)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_31.addWidget(self.label_5)
        self.gridLayout.addLayout(self.horizontalLayout_31, 6, 8, 1, 2)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_32.addWidget(self.label_4)
        self.gridLayout.addLayout(self.horizontalLayout_32, 4, 8, 1, 2)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setSpacing(1)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_39.addWidget(self.line)
        self.gridLayout.addLayout(self.horizontalLayout_39, 3, 8, 1, 4)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_46.addWidget(self.line_7)
        self.gridLayout.addLayout(self.horizontalLayout_46, 13, 8, 1, 4)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_44.addWidget(self.line_5)
        self.gridLayout.addLayout(self.horizontalLayout_44, 9, 8, 1, 4)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_43.addWidget(self.line_4)
        self.gridLayout.addLayout(self.horizontalLayout_43, 7, 8, 1, 4)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_45.addWidget(self.line_6)
        self.gridLayout.addLayout(self.horizontalLayout_45, 11, 8, 1, 4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout.addLayout(self.horizontalLayout_10, 17, 10, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.HomeButton = QtWidgets.QPushButton(self.tab)
        self.HomeButton.setMaximumSize(QtCore.QSize(150, 50))
        self.HomeButton.setObjectName("HomeButton")
        self.horizontalLayout.addWidget(self.HomeButton)
        self.gridLayout.addLayout(self.horizontalLayout, 17, 11, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.NextPic = QtWidgets.QPushButton(self.tab)
        self.NextPic.setMaximumSize(QtCore.QSize(150, 50))
        self.NextPic.setObjectName("NextPic")
        self.horizontalLayout_4.addWidget(self.NextPic)
        self.gridLayout.addLayout(self.horizontalLayout_4, 17, 6, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ThermImg = QtWidgets.QPushButton(self.tab)
        self.ThermImg.setMaximumSize(QtCore.QSize(150, 50))
        self.ThermImg.setObjectName("ThermImg")
        self.horizontalLayout_5.addWidget(self.ThermImg)
        self.gridLayout.addLayout(self.horizontalLayout_5, 17, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.PrevPic = QtWidgets.QPushButton(self.tab)
        self.PrevPic.setMaximumSize(QtCore.QSize(150, 50))
        self.PrevPic.setObjectName("PrevPic")
        self.horizontalLayout_6.addWidget(self.PrevPic)
        self.gridLayout.addLayout(self.horizontalLayout_6, 17, 0, 1, 1)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.PressRead = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PressRead.setFont(font)
        self.PressRead.setAlignment(QtCore.Qt.AlignCenter)
        self.PressRead.setObjectName("PressRead")
        self.horizontalLayout_33.addWidget(self.PressRead)
        self.gridLayout.addLayout(self.horizontalLayout_33, 14, 10, 1, 2)
        self.image = QtWidgets.QLabel(self.tab)
        self.image.setMaximumSize(QtCore.QSize(900, 850))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("Normal_Image/image(0).jpg"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 0, 0, 17, 8)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_18.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_18, 0, 8, 1, 4)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.TempRead = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.TempRead.setFont(font)
        self.TempRead.setAlignment(QtCore.Qt.AlignCenter)
        self.TempRead.setObjectName("TempRead")
        self.horizontalLayout_38.addWidget(self.TempRead)
        self.gridLayout.addLayout(self.horizontalLayout_38, 4, 10, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 10, 1, 2)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_47.addWidget(self.line_8)
        self.gridLayout.addLayout(self.horizontalLayout_47, 15, 8, 1, 4)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.AccelRead = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AccelRead.setFont(font)
        self.AccelRead.setAlignment(QtCore.Qt.AlignCenter)
        self.AccelRead.setObjectName("AccelRead")
        self.horizontalLayout_35.addWidget(self.AccelRead)
        self.gridLayout.addLayout(self.horizontalLayout_35, 10, 10, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.HoverButton = QtWidgets.QPushButton(self.tab)
        self.HoverButton.setMaximumSize(QtCore.QSize(150, 50))
        self.HoverButton.setObjectName("HoverButton")
        self.horizontalLayout_7.addWidget(self.HoverButton)
        self.gridLayout.addLayout(self.horizontalLayout_7, 17, 8, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        
        TabWidget.addTab(self.tab, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.alt_label = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alt_label.setFont(font)
        self.alt_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alt_label.setObjectName("alt_label")
        self.horizontalLayout_70.addWidget(self.alt_label)
        self.gridLayout_4.addLayout(self.horizontalLayout_70, 3, 2, 1, 1)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.label_21 = QtWidgets.QLabel(self.tab1)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_69.addWidget(self.label_21)
        spacerItem = QtWidgets.QSpacerItem(700, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_69.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.horizontalLayout_69, 0, 0, 6, 1)
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.long_label = QtWidgets.QLabel(self.tab1)
        self.long_label.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.long_label.setFont(font)
        self.long_label.setAlignment(QtCore.Qt.AlignCenter)
        self.long_label.setObjectName("long_label")
        self.horizontalLayout_79.addWidget(self.long_label)
        self.gridLayout_4.addLayout(self.horizontalLayout_79, 2, 2, 1, 1)
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.latitude_label = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.latitude_label.setFont(font)
        self.latitude_label.setAlignment(QtCore.Qt.AlignCenter)
        self.latitude_label.setObjectName("latitude_label")
        self.horizontalLayout_80.addWidget(self.latitude_label)
        self.gridLayout_4.addLayout(self.horizontalLayout_80, 1, 2, 1, 1)
        self.horizontalLayout_82 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_82.setObjectName("horizontalLayout_82")
        self.lext_long_label = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lext_long_label.setFont(font)
        self.lext_long_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lext_long_label.setObjectName("lext_long_label")
        self.horizontalLayout_82.addWidget(self.lext_long_label)
        self.gridLayout_4.addLayout(self.horizontalLayout_82, 2, 3, 1, 1)
        self.horizontalLayout_81 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_81.setObjectName("horizontalLayout_81")
        self.next_lat_label = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.next_lat_label.setFont(font)
        self.next_lat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.next_lat_label.setObjectName("next_lat_label")
        self.horizontalLayout_81.addWidget(self.next_lat_label)
        self.gridLayout_4.addLayout(self.horizontalLayout_81, 1, 3, 1, 1)
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_77.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.rem_waypoint = QtWidgets.QPushButton(self.tab1)
        self.rem_waypoint.setMaximumSize(QtCore.QSize(150, 50))
        self.rem_waypoint.setObjectName("rem_waypoint")
        self.horizontalLayout_77.addWidget(self.rem_waypoint)
        self.gridLayout_4.addLayout(self.horizontalLayout_77, 4, 4, 1, 1)
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.hover_button = QtWidgets.QPushButton(self.tab1)
        self.hover_button.setMaximumSize(QtCore.QSize(150, 50))
        self.hover_button.setObjectName("hover_button")
        self.horizontalLayout_74.addWidget(self.hover_button)
        self.gridLayout_4.addLayout(self.horizontalLayout_74, 5, 3, 1, 1)
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.emerg_land_button = QtWidgets.QPushButton(self.tab1)
        self.emerg_land_button.setMaximumSize(QtCore.QSize(150, 50))
        self.emerg_land_button.setObjectName("emerg_land_button")
        self.horizontalLayout_73.addWidget(self.emerg_land_button)
        self.gridLayout_4.addLayout(self.horizontalLayout_73, 5, 4, 1, 1)
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.send_command_button = QtWidgets.QPushButton(self.tab1)
        self.send_command_button.setMinimumSize(QtCore.QSize(150, 50))
        self.send_command_button.setMaximumSize(QtCore.QSize(150, 50))
        self.send_command_button.setObjectName("send_command_button")
        self.horizontalLayout_76.addWidget(self.send_command_button)
        self.gridLayout_4.addLayout(self.horizontalLayout_76, 4, 3, 1, 1)
        self.horizontalLayout_83 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_83.setObjectName("horizontalLayout_83")
        self.next_alt_label = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.next_alt_label.setFont(font)
        self.next_alt_label.setAlignment(QtCore.Qt.AlignCenter)
        self.next_alt_label.setObjectName("next_alt_label")
        self.horizontalLayout_83.addWidget(self.next_alt_label)
        self.gridLayout_4.addLayout(self.horizontalLayout_83, 3, 3, 1, 1)
        self.horizontalLayout_84 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_84.setObjectName("horizontalLayout_84")
        self.label_23 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_84.addWidget(self.label_23)
        self.gridLayout_4.addLayout(self.horizontalLayout_84, 0, 2, 1, 1)
        self.horizontalLayout_85 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_85.setObjectName("horizontalLayout_85")
        self.label_22 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_85.addWidget(self.label_22)
        self.gridLayout_4.addLayout(self.horizontalLayout_85, 0, 1, 1, 1)
        self.horizontalLayout_86 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_86.setObjectName("horizontalLayout_86")
        self.label_25 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_86.addWidget(self.label_25)
        self.gridLayout_4.addLayout(self.horizontalLayout_86, 1, 1, 1, 1)
        self.horizontalLayout_87 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_87.setObjectName("horizontalLayout_87")
        self.label_26 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_87.addWidget(self.label_26)
        self.gridLayout_4.addLayout(self.horizontalLayout_87, 2, 1, 1, 1)
        self.horizontalLayout_88 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_88.setObjectName("horizontalLayout_88")
        self.label_27 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_88.addWidget(self.label_27)
        self.gridLayout_4.addLayout(self.horizontalLayout_88, 3, 1, 1, 1)
        self.horizontalLayout_89 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_89.setObjectName("horizontalLayout_89")
        self.label_24 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_89.addWidget(self.label_24)
        self.gridLayout_4.addLayout(self.horizontalLayout_89, 0, 3, 1, 1)
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.location_list = QtWidgets.QListWidget(self.tab1)
        self.location_list.setMinimumSize(QtCore.QSize(300, 500))
        self.location_list.setMaximumSize(QtCore.QSize(300, 500))
        self.location_list.setObjectName("location_list")
        self.horizontalLayout_78.addWidget(self.location_list)
        self.gridLayout_4.addLayout(self.horizontalLayout_78, 0, 4, 4, 1)
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.add_waypoint_button = QtWidgets.QPushButton(self.tab1)
        self.add_waypoint_button.setMinimumSize(QtCore.QSize(150, 50))
        self.add_waypoint_button.setMaximumSize(QtCore.QSize(150, 50))
        self.add_waypoint_button.setObjectName("add_waypoint_button")
        self.horizontalLayout_75.addWidget(self.add_waypoint_button)
        self.gridLayout_4.addLayout(self.horizontalLayout_75, 4, 1, 1, 1)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.return_base_button = QtWidgets.QPushButton(self.tab1)
        self.return_base_button.setMaximumSize(QtCore.QSize(150, 50))
        self.return_base_button.setObjectName("return_base_button")
        self.horizontalLayout_71.addWidget(self.return_base_button)
        self.gridLayout_4.addLayout(self.horizontalLayout_71, 5, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        
        
        
        TabWidget.addTab(self.tab1, "")
        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget"))
        self.HumRead.setText(_translate("TabWidget", "18"))
        self.MagnetRead.setText(_translate("TabWidget", "North"))
        self.LightRead.setText(_translate("TabWidget", "12"))
        self.NormImg.setText(_translate("TabWidget", "Normal Image"))
        self.label_2.setText(_translate("TabWidget", "Sensor"))
        self.label_7.setText(_translate("TabWidget", "Acceleration"))
        self.label_9.setText(_translate("TabWidget", "Pressure"))
        self.label_8.setText(_translate("TabWidget", "Magnetometer"))
        self.label_6.setText(_translate("TabWidget", "Light"))
        self.label_10.setText(_translate("TabWidget", "Altitude"))
        self.AltRead.setText(_translate("TabWidget", "46 m"))
        self.label_5.setText(_translate("TabWidget", "Humidity"))
        self.label_4.setText(_translate("TabWidget", "Temperature"))
        self.HomeButton.setText(_translate("TabWidget", "Return Home"))
        self.NextPic.setText(_translate("TabWidget", "Next Picture"))
        self.ThermImg.setText(_translate("TabWidget", "Thermal Image"))
        self.PrevPic.setText(_translate("TabWidget", "Previous Picture"))
        self.PressRead.setText(_translate("TabWidget", "200 Pa"))
        self.label.setText(_translate("TabWidget", "Battery Level"))
        self.TempRead.setText(_translate("TabWidget", "5C"))
        self.label_3.setText(_translate("TabWidget", "Measurement"))
        self.AccelRead.setText(_translate("TabWidget", "22 km/h"))
        self.HoverButton.setText(_translate("TabWidget", "Hover"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Tab 1"))
        self.alt_label.setText(_translate("TabWidget", "25 m"))
        self.label_21.setText(_translate("TabWidget", "TextLabel"))
        self.long_label.setText(_translate("TabWidget", "1548.6945"))
        self.latitude_label.setText(_translate("TabWidget", "1254.3654"))
        self.lext_long_label.setText(_translate("TabWidget", "next long"))
        self.next_lat_label.setText(_translate("TabWidget", "next lat"))
        self.rem_waypoint.setText(_translate("TabWidget", "Remove Waypoint"))
        self.hover_button.setText(_translate("TabWidget", "Hover"))
        self.emerg_land_button.setText(_translate("TabWidget", "Emergency Land"))
        self.send_command_button.setText(_translate("TabWidget", "Send Command"))
        self.next_alt_label.setText(_translate("TabWidget", "next alt"))
        self.label_23.setText(_translate("TabWidget", "<html><head/><body><p>Current</p><p>Reading</p></body></html>"))
        self.label_22.setText(_translate("TabWidget", "Direction"))
        self.label_25.setText(_translate("TabWidget", "Latitude"))
        self.label_26.setText(_translate("TabWidget", "Longitude"))
        self.label_27.setText(_translate("TabWidget", "Altitude"))
        self.label_24.setText(_translate("TabWidget", "<html><head/><body><p>Next</p><p>Location</p></body></html>"))
        self.add_waypoint_button.setText(_translate("TabWidget", "Add Waypoint"))
        self.return_base_button.setText(_translate("TabWidget", "Return Home"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab1), _translate("TabWidget", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

